Test script

diff --git a/buildspec.yaml b/buildspec.yaml
--- a/buildspec.yaml
+++ b/buildspec.yaml
@@ -11,6 +11,12 @@ phases:
       docker: 18
   pre_build:
     commands:
+      - if ! command -v terraform &> /dev/null
+then
+    echo "terraform could not be found"
+    exit
+fi
+
       - echo Logging in to Amazon ECR...
       - aws --version
       - $(aws ecr get-login --region ${ECR_REGION} --no-include-email)
